# Generated by Django 4.1.7 on 2023-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_endereco_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
    ]
