# Generated by Django 4.1.7 on 2023-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('descricao_curta', models.TextField(max_length=255, verbose_name='descrição curta')),
                ('descricao_longa', models.TextField(verbose_name='descrição longa')),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d', verbose_name='imagem')),
                ('slug', models.SlugField()),
                ('preco_marketing', models.FloatField()),
                ('preco_marketing_promocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
