# Generated by Django 4.1.7 on 2023-03-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_promocional',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
